apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: books.example.kaimal.net
spec:
  group: example.kaimal.net
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                title:
                  type: string
                authors:
                  type: array
                  items:
                    type: string
  scope: Namespaced
  names:
    plural: books
    singular: book
    kind: Book